language: php

php:
  - '7.0'

sudo: false

services:
  - docker

env:
  global:
  - MOZILLIANS_KEY=null
  - BUILT_CONTAINER_NAME="$TRAVIS_REPO_SLUG:$TRAVIS_BRANCH"

cache:
  directories:
  - $HOME/.composer/cache

install:
  - npm install -g bower
  - composer install

script: phpunit -c app/

after_success:
  - docker build -t="$BUILT_CONTAINER_NAME" .
#notifications:
#  irc: "irc.mozilla.org#mozilla.ch"
